### PR TITLE
Move example directory out off library to help contributors to get started

### PR DESCRIPTION
**Pull request by maxme**
This is the first PR of a series to add new features to the library (`notifyItemMoved`).

This should help other contributors to use the example app.

### CODE REVIEW

**Comment by godness84** [comment]
Thank you very much @maxme for your contributions! I watched on your repo and it seems that you moved the library back to the root dir in more recent commits, didn't you? Is there any problem with moving the library in its own folder?

**Comment by maxme** [comment]
That's right, having the library's code in `library` wasn't a good idea after all, it simplifies development with the example app but was creating other issues with npm when I added it as a dependency.

I found another way to make changes to the library and test them in the example app easily without changing the directory structure. I'll likely close this and the following PRs and open another one (or eventually a couple of them).

Sorry for the back/forth that's my first RN library ;).

**Comment by godness84** [comment]
No problem at all, looking forward for your new commits :)
I had troubles too in having an easy way to work on lib and example code at the same time.

Do you have plans for some other features that you need?

**Comment by maxme** [comment]
> Do you have plans for some other features that you need?

Yes, I might add iOS support.

**Comment by maxme** [comment]
I'm closing this and #16, #17 - I'll open a PR with the same features but without the directory changes soon.

**Pull request closed without merging**
